#!/usr/bin/env python3

# need to exec this:
# xinput --set-prop 10 'libinput Accel Speed' -0.9

import sys
import subprocess

devid = 10
if len(sys.argv) > 1:
    devid = sys.argv[1]

speed = "-0.9"
if len(sys.argv) > 2:
    speed = sys.argv[2]

subprocess.run(["xinput", "--set-prop", str(devid),  'libinput Accel Speed', str(speed)])

